=== Aerobota/geocat/web/src/main/webResources/WEB-INF/wro-sources.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sources" type="sourcesType"/>
  <xs:complexType name="jsSourceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="webapp" use="required"/>
        <xs:attribute type="xs:string" name="pathOnDisk" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="requireType">
    <xs:sequence>
      <xs:element type="jsSourceType" name="jsSource" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="cssSourceType" name="cssSource" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="pathOnDisk"/>
  </xs:complexType>
  <xs:complexType name="includeType">
    <xs:attribute type="xs:string" name="file" use="required"/>
  </xs:complexType>
  <xs:complexType name="sourcesType">
    <xs:sequence>
      <xs:element type="includeType" name="include" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="requireType" name="require" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="declarativeType" name="declarative" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="declarativeType">
    <xs:sequence>
      <xs:element type="jsSourceType" name="jsSource" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="cssSourceType" name="cssSource" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="pathOnDisk" use="optional"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  <xs:complexType name="cssSourceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="webapp" use="required"/>
        <xs:attribute type="xs:string" name="pathOnDisk" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== Aerobota/geocat/web-ui/src/main/resources/web-ui-wro-sources.xml
<sources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../web/src/main/webResources/WEB-INF/wro-sources.xsd" >
    <require pathOnDisk="web-ui/src/main/resources" >
        <jsSource webappPath="catalog/js" />
        <jsSource webappPath="catalog/components" pathOnDisk="${project.basedir}/../web-ui/src/main/resources" />
        <cssSource webappPath="catalog/style" pathOnDisk="${project.basedir}/../web-ui/src/main/resources" />
    </require>
    <declarative name="lib" pathOnDisk="web-ui/src/main/resources">
            <jsSource webappPath="catalog/lib/modernizr.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/jquery-2.0.3.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/moment+langs.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular/angular.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular/angular-resource.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular/angular-route.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular-translate.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular-md5.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular.ext/datetimepicker.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/bootstrap-3.0.1.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/proj4js-compressed.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/ol.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/d3.v3.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/nv.d3.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/jquery.ext/jquery.ui.widget.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/jquery.ext/jquery.iframe-transport.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/jquery.ext/jquery.fileupload.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/jquery.ext/jquery.fileupload-process.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/jquery.ext/jquery.fileupload-angular.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/bootstrap.ext/typeahead.js/typeahead.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/bootstrap.ext/tagsinput/bootstrap-tagsinput.min.js" minimize="false"/>
    </declarative>
    <declarative name="inspire-lib" pathOnDisk="web-ui/src/main/resources">
            <jsSource webappPath="catalog/lib/modernizr.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/jquery-2.0.3.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/moment+langs.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular/angular.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular/angular-resource.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular/angular-route.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/angular-translate.min.js" minimize="false"/>
            <jsSource webappPath="catalog/lib/bootstrap-3.0.1.min.js" minimize="false"/>
    </declarative>

</sources>
